apiVersion: v2
name: gatekeeper-library
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/website/static/img/logo.svg
type: application
version: 0.1.2
appVersion: bd942ad8afd316743fbe97a69c5019d349c1a5c1
sources:
  - https://github.com/jouve/charts
  - https://github.com/open-policy-agent/gatekeeper-library
maintainers:
  - name: jouve
    url: https://github.com/jouve
annotations:
  artifacthub.io/license: Apache-2.0
