apiVersion: v2
name: gatekeeper-library
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/website/static/img/logo.svg
type: application
version: 0.1.3
appVersion: 0d95b7608c2ca835ba0418bd1199c3d8f6c9c6e1
sources:
  - https://github.com/jouve/charts
  - https://github.com/open-policy-agent/gatekeeper-library
maintainers:
  - name: jouve
    url: https://github.com/jouve
annotations:
  artifacthub.io/license: Apache-2.0
