{{- if .Values.autoscaler.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "coredns.fullname" . }}-autoscaler
  namespace:  {{ .Release.Namespace }}
  labels: {{- include "coredns.labels.autoscaler" . | nindent 4 }}
    {{- if .Values.customLabels }}
    {{- toYaml .Values.customLabels | nindent 4 }}
    {{- end }}
  {{- with merge .Values.autoscaler.configmap.annotations .Values.customAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  # When cluster is using large nodes(with more cores), "coresPerReplica" should dominate.
  # If using small nodes, "nodesPerReplica" should dominate.
  linear: |-
    {
      "coresPerReplica": {{ .Values.autoscaler.coresPerReplica | float64 }},
      "nodesPerReplica": {{ .Values.autoscaler.nodesPerReplica | float64 }},
      "preventSinglePointFailure": {{ .Values.autoscaler.preventSinglePointFailure }},
      "min": {{ .Values.autoscaler.min | int }},
      "max": {{ .Values.autoscaler.max | int }},
      "includeUnschedulableNodes": {{ .Values.autoscaler.includeUnschedulableNodes }}
    }
{{- end }}
