{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "coredns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "coredns.labels" . | nindent 4 }}
    {{- if .Values.customLabels }}
    {{ toYaml .Values.customLabels | indent 4 }}
    {{- end }}
  {{- with .Values.customAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      {{- if .Values.isClusterService }}
      k8s-app: {{ template "coredns.k8sapplabel" . }}
      {{- end }}
      app.kubernetes.io/name: {{ template "coredns.name" . }}
    ingress:
      - {{- if not .Values.isClusterService }}
        {{- $_ := eq .Values.networkPolicy.ingress.dns.peers nil | ternary "" "-" | required "required value networkPolicy.ingress.dns.peers" }}
        from: {{ .Values.networkPolicy.ingress.dns.peers | toYaml | nindent 10 }}
        {{- end }}
        ports:
          - protocol: TCP
            port: 53
          - protocol: UDP
            port: 53
      {{- with .Values.networkPolicy.ingress.metrics.peers }}
      - from: {{ . | toYaml | nindent 10 }}
        ports:
          - protocol: TCP
            port: 9153
      {{- end }}
      {{- with .Values.networkPolicy.ingress.rules }}
      {{- . | toYaml | nindent 8 }}
      {{- end }}
    {{- with .Values.networkPolicy.egress.rules }}
    egress:
      {{- . | toYaml | nindent 8 }}
    {{- end }}
    policyTypes:
      - Ingress
      - Egress
{{- end }}
