apiVersion: {{ template "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "common.names.fullname" . }}-view
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" . ) | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  {{- with .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - hnc.x-k8s.io
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
---
apiVersion: {{ template "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "common.names.fullname" . }}-edit
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" . ) | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  {{- with .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - hnc.x-k8s.io
    resources:
      - '*'
    verbs:
      - create
      - update
      - patch
      - delete
