{{- if and .Values.certManager.enabled (not .Values.issuerRef) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "common.names.fullname" . }}-selfsigned-issuer
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" . ) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selfSigned: {}
{{- end }}
