apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}-webhook-service
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" . ) | nindent 4 }}
    control-plane: controller-manager
  {{- with include "common.tplvalues.merge" ( dict "values" (list .Values.service.annotations .Values.commonAnnotations) "context" . ) | fromYaml }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.podLabels .Values.commonLabels ) "context" . ) | fromYaml }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: webhook-server
