apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if and .Values.persistence.enabled (eq (index .Values.persistence.accessModes 0) "ReadWriteOnce") }}
  strategy:
    type: Recreate
  {{- else if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: mailpit
          image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          args:
          - --db-file
          - /var/lib/mailpit/mailpit.db
          {{- if .Values.ingress.enabled }}
          - --webroot
          - {{ .Values.ingress.path }}
          {{- end }}
          {{- if .Values.mailpit.ui.authFile.enabled }}
          - --ui-auth-file
          - /etc/mailpit/ui.htpasswd
          {{- end }}
          {{- if .Values.mailpit.ui.tls.enabled }}
          - --ui-tls-cert
          - /etc/mailpit/ui.crt
          - --ui-tls-key
          - /etc/mailpit/ui.key
          {{- end }}
          {{- if .Values.mailpit.smtp.authFile.enabled }}
          - --smtp-auth-file
          - /etc/mailpit/smtp.htpasswd
          {{- if not .Values.mailpit.smtp.tls.enabled }}
          - --smtp-auth-allow-insecure
          {{- end }}
          {{- end }}
          {{- if .Values.mailpit.smtp.tls.enabled }}
          - --smtp-tls-cert
          - /etc/mailpit/smtp.crt
          - --smtp-tls-key
          - /etc/mailpit/smtp.key
          {{- end }}
          {{- if .Values.image.debug }}
          - --verbose
          {{- end }}
          {{- with .Values.args }}
          {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnvVars }}
          env: {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- range $name, $containerPort := .Values.containerPorts }}
            - name: {{ $name }}
              containerPort: {{ $containerPort }}
            {{- end }}
          volumeMounts:
          - name: data
            mountPath: /var/lib/mailpit
          {{- if or .Values.mailpit.ui.authFile.enabled .Values.mailpit.ui.authFile.enabled .Values.mailpit.ui.tls.secretName .Values.mailpit.smtp.tls.secretName }}
          - name: etc
            mountPath: /etc/mailpit
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
          {{- end }}
        {{- with .Values.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" . "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        {{- if or .Values.mailpit.ui.authFile.enabled .Values.mailpit.ui.authFile.enabled .Values.mailpit.ui.tls.secretName .Values.mailpit.smtp.tls.secretName }}
        - name: etc
          projected:
            sources:
            {{- if or .Values.mailpit.ui.authFile.enabled .Values.mailpit.ui.authFile.enabled }}
            - secret:
                name: {{ template "common.names.fullname" . }}
            {{- end }}
            {{- if .Values.mailpit.ui.tls.enabled }}
            - secret:
                name: {{ .Values.mailpit.ui.tls.secretName }}
              items:
              - key: tls.crt
                path: ui.crt
              - key: tls.key
                path: ui.key
            {{- end }}
            {{- if .Values.mailpit.smtp.tls.enabled }}
            - secret:
                name: {{ .Values.mailpit.smtp.tls.secretName }}
              items:
              - key: tls.crt
                path: smtp.crt
              - key: tls.key
                path: smtp.key
            {{- end }}
        {{- end }}
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (include "common.names.fullname" .) .Values.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
