name: setup-chart-testing
description: Setup Chart Testing
inputs:
  url:
    description: plugin url
    required: true
  version:
    description: plugin version
    required: true
runs:
  using: "composite"
  steps:
    - name: Download plugin
      shell: bash
      run: |
        cache_dir=${RUNNER_TOOL_CACHE}/ct/${{ inputs.version }}/x86_64
        mkdir -p "${cache_dir}"
        curl -fsSL ${{ inputs.url }}/releases/download/v${{ inputs.version }}/chart-testing_${{ inputs.version }}_linux_amd64.tar.gz | tar -C "${cache_dir}" -xz

        echo 'Setting CT_CONFIG_DIR...'
        echo "CT_CONFIG_DIR=${cache_dir}/etc" >> "${GITHUB_ENV}"

        echo 'Configuring environment variables for virtual environment for subsequent workflow steps...'
        echo "${cache_dir}" >> "${GITHUB_PATH}"
