{{- if .Values.networkPolicy.enabled }}
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: {{ template "common.names.fullname" . }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: {{ template "common.names.fullname" . }}
      ports:
        - protocol: TCP
          port: postgresql
    {{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled }}
    - from:
        {{- with .Values.networkPolicy.scrapePeer }}
        - {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 10 }}
        {{- else }}
        - namespaceSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: metrics
    {{- end }}
    - from:
        {{- with .Values.networkPolicy.cnpgPeer }}
        - {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 10 }}
        {{- else }}
        - namespaceSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: status
    {{- with .Values.networkPolicy.ingressRules }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: {{ template "common.names.fullname" . }}
      ports:
        - protocol: TCP
          port: postgresql
    - to:
        {{- with .Values.networkPolicy.apiServerPeer }}
        - {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 10 }}
        {{- else }}
        - ipBlock:
            cidr: 0.0.0.0/0
        {{- end }}
      ports:
        - protocol: TCP
          port: 6443
    - to:
        {{- with .Values.networkPolicy.cnpgPeer }}
        - {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 10 }}
        {{- else }}
        - namespaceSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: webhook-server
    {{- if .Values.backup.s3.objectBucketClaim.enabled }}
    - to:
        {{- with .Values.networkPolicy.objectStoragePeer }}
        - {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 10 }}
        {{- else }}
        - namespaceSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: 8080
    {{- end }}
    {{- with .Values.networkPolicy.egressRules }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
