{{- if .Values.networkPolicy.enabled }}
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" . ) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: {{ template "common.names.fullname" . }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: {{ template "common.names.fullname" . }}
      ports:
        - protocol: TCP
          port: 5432
    {{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled }}
    - from:
        {{- with .Values.networkPolicy.metrics.peer }}
        - {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 10 }}
        {{- else }}
        - namespaceSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: 9187
    {{- end }}
    - from:
        {{- with .Values.networkPolicy.cnpg.peer }}
        - {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 10 }}
        {{- else }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cnpg-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cloudnative-pg
        {{- end }}
      ports:
        - protocol: TCP
          port: 8000
    {{- with .Values.networkPolicy.ingressRules }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: {{ template "common.names.fullname" . }}
      ports:
        - protocol: TCP
          port: 5432
    - {{- with .Values.networkPolicy.apiserver.peer }}
      to:
        - {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 10 }}
      {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.apiserver.port }}
    - to:
        {{- with .Values.networkPolicy.cnpg.peer }}
        - {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 10 }}
        {{- else }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cnpg-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cloudnative-pg
        {{- end }}
      ports:
        - protocol: TCP
          port: 9443
    {{- if .Values.backup.enabled }}
    - {{- with .Values.networkPolicy.backup.peer }}
      to:
        - {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 10 }}
      {{- end }}
      ports:
        - protocol: TCP
          {{- $url := urlParse .Values.backup.endpointURL }}
          {{- $port := 0 }}
          {{- if contains ":" $url.host }}
          {{- $port = splitList ":" $url.host | last }}
          {{- else }}
          {{- $port = eq $url.scheme "https" | ternary 443 80 }}
          {{- end }}
          port: {{ $port }}
    {{- end }}
    {{- with .Values.networkPolicy.egressRules }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
