apiVersion: v2
name: mailpit
description: An email and SMTP testing tool with API for developers
type: application
version: 0.2.6
appVersion: 1.6.18
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
sources:
- https://github.com/jouve/charts
- https://github.com/axllent/mailpit
maintainers:
- name: jouve
  url: https://github.com/jouve
annotations:
  artifacthub.io/license: GPL-3.0-or-later
