apiVersion: v2
name: postgresql
description: Deploy postgresql using cloudnative-pg operator
type: application
version: 0.1.1
appVersion: "15.3"
sources:
- https://github.com/jouve/charts
- https://cloudnative-pg.io/
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
maintainers:
- name: jouve
  url: https://github.com/jouve
