apiVersion: v2
name: postgresql
description: Deploy postgresql using cloudnative-pg operator
type: application
version: 0.2.0
appVersion: "15.3"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
sources:
- https://github.com/jouve/charts
- https://cloudnative-pg.io/
maintainers:
- name: jouve
  url: https://github.com/jouve
